-- Migration 002: Kasino Schema (MOVED)
--
-- Kasino tables have been migrated to their own database: kasino
-- See /opt/kasino/backend/schema.sql for the canonical schema.
-- This migration is intentionally empty to preserve numbering.
